title: Adrienne Tuynman
position: Ph.D. Student
affiliation: Scool team, Inria of Lille
email: firstname.lastname (at) inria.fr
keywords: reinforcement learning, bandits
google_scholar: 
github_link: 
linkedin: 
cv_link: 
avatar: ./assets/img/photo.JPG
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: My personal homepage
canonical: atuynman.github.io
remote_theme: yaoyao-liu/strata-academic
